FROM golang:latest AS build

WORKDIR /go/src

COPY go.mod main.go /go/src

RUN CGO_ENABLED=0 go mod download

COPY main.go /src

RUN go build

FROM scratch

COPY --from=build /go/src/docker-go /

CMD ["./docker-go"]